syntax = "proto3";

package slotMachine;

service SlotMachine {
  rpc RandomPlay (EmptyRequest) returns (RandomPlayResponse);
  rpc CalculateJackpot (CalculateJackpotRequest) returns (CalculateJackpotResponse);
}

message EmptyRequest {}

message RandomPlayResponse {
  string slot0 = 1;
  string slot1 = 2;
  string slot2 = 3;
}

message CalculateJackpotRequest {
  string slot0 = 1;
  string slot1 = 2;
  string slot2 = 3;
  double bet = 4;
}

message CalculateJackpotResponse {
  double profit = 1;
  string result = 2;
  string slot0 = 3;
  string slot1 = 4;
  string slot2 = 5;
}