// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: calculator.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "calculator";

export interface AddRequest {
  a: number;
  b: number;
}

export interface AddResponse {
  result: number;
}

function createBaseAddRequest(): AddRequest {
  return { a: 0, b: 0 };
}

export const AddRequest: MessageFns<AddRequest> = {
  encode(message: AddRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.a !== 0) {
      writer.uint32(8).int32(message.a);
    }
    if (message.b !== 0) {
      writer.uint32(16).int32(message.b);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.a = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.b = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddRequest {
    return {
      a: isSet(object.a) ? globalThis.Number(object.a) : 0,
      b: isSet(object.b) ? globalThis.Number(object.b) : 0,
    };
  },

  toJSON(message: AddRequest): unknown {
    const obj: any = {};
    if (message.a !== 0) {
      obj.a = Math.round(message.a);
    }
    if (message.b !== 0) {
      obj.b = Math.round(message.b);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddRequest>, I>>(base?: I): AddRequest {
    return AddRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddRequest>, I>>(object: I): AddRequest {
    const message = createBaseAddRequest();
    message.a = object.a ?? 0;
    message.b = object.b ?? 0;
    return message;
  },
};

function createBaseAddResponse(): AddResponse {
  return { result: 0 };
}

export const AddResponse: MessageFns<AddResponse> = {
  encode(message: AddResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== 0) {
      writer.uint32(8).int32(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddResponse {
    return { result: isSet(object.result) ? globalThis.Number(object.result) : 0 };
  },

  toJSON(message: AddResponse): unknown {
    const obj: any = {};
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddResponse>, I>>(base?: I): AddResponse {
    return AddResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddResponse>, I>>(object: I): AddResponse {
    const message = createBaseAddResponse();
    message.result = object.result ?? 0;
    return message;
  },
};

export type CalculatorService = typeof CalculatorService;
export const CalculatorService = {
  add: {
    path: "/calculator.Calculator/Add",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AddRequest): Buffer => Buffer.from(AddRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddRequest => AddRequest.decode(value),
    responseSerialize: (value: AddResponse): Buffer => Buffer.from(AddResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddResponse => AddResponse.decode(value),
  },
} as const;

export interface CalculatorServer extends UntypedServiceImplementation {
  add: handleUnaryCall<AddRequest, AddResponse>;
}

export interface CalculatorClient extends Client {
  add(request: AddRequest, callback: (error: ServiceError | null, response: AddResponse) => void): ClientUnaryCall;
  add(
    request: AddRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AddResponse) => void,
  ): ClientUnaryCall;
  add(
    request: AddRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AddResponse) => void,
  ): ClientUnaryCall;
}

export const CalculatorClient = makeGenericClientConstructor(CalculatorService, "calculator.Calculator") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CalculatorClient;
  service: typeof CalculatorService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
