// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: slotMachine.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "slotMachine";

export interface EmptyRequest {
}

export interface RandomPlayResponse {
  slot0: string;
  slot1: string;
  slot2: string;
}

export interface CalculateJackpotRequest {
  slot0: string;
  slot1: string;
  slot2: string;
  bet: number;
}

export interface CalculateJackpotResponse {
  profit: number;
  result: string;
  slot0: string;
  slot1: string;
  slot2: string;
}

function createBaseEmptyRequest(): EmptyRequest {
  return {};
}

export const EmptyRequest: MessageFns<EmptyRequest> = {
  encode(_: EmptyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyRequest {
    return {};
  },

  toJSON(_: EmptyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyRequest>, I>>(base?: I): EmptyRequest {
    return EmptyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyRequest>, I>>(_: I): EmptyRequest {
    const message = createBaseEmptyRequest();
    return message;
  },
};

function createBaseRandomPlayResponse(): RandomPlayResponse {
  return { slot0: "", slot1: "", slot2: "" };
}

export const RandomPlayResponse: MessageFns<RandomPlayResponse> = {
  encode(message: RandomPlayResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slot0 !== "") {
      writer.uint32(10).string(message.slot0);
    }
    if (message.slot1 !== "") {
      writer.uint32(18).string(message.slot1);
    }
    if (message.slot2 !== "") {
      writer.uint32(26).string(message.slot2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RandomPlayResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRandomPlayResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slot0 = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.slot1 = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.slot2 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RandomPlayResponse {
    return {
      slot0: isSet(object.slot0) ? globalThis.String(object.slot0) : "",
      slot1: isSet(object.slot1) ? globalThis.String(object.slot1) : "",
      slot2: isSet(object.slot2) ? globalThis.String(object.slot2) : "",
    };
  },

  toJSON(message: RandomPlayResponse): unknown {
    const obj: any = {};
    if (message.slot0 !== "") {
      obj.slot0 = message.slot0;
    }
    if (message.slot1 !== "") {
      obj.slot1 = message.slot1;
    }
    if (message.slot2 !== "") {
      obj.slot2 = message.slot2;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RandomPlayResponse>, I>>(base?: I): RandomPlayResponse {
    return RandomPlayResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RandomPlayResponse>, I>>(object: I): RandomPlayResponse {
    const message = createBaseRandomPlayResponse();
    message.slot0 = object.slot0 ?? "";
    message.slot1 = object.slot1 ?? "";
    message.slot2 = object.slot2 ?? "";
    return message;
  },
};

function createBaseCalculateJackpotRequest(): CalculateJackpotRequest {
  return { slot0: "", slot1: "", slot2: "", bet: 0 };
}

export const CalculateJackpotRequest: MessageFns<CalculateJackpotRequest> = {
  encode(message: CalculateJackpotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slot0 !== "") {
      writer.uint32(10).string(message.slot0);
    }
    if (message.slot1 !== "") {
      writer.uint32(18).string(message.slot1);
    }
    if (message.slot2 !== "") {
      writer.uint32(26).string(message.slot2);
    }
    if (message.bet !== 0) {
      writer.uint32(33).double(message.bet);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculateJackpotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateJackpotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slot0 = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.slot1 = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.slot2 = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.bet = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateJackpotRequest {
    return {
      slot0: isSet(object.slot0) ? globalThis.String(object.slot0) : "",
      slot1: isSet(object.slot1) ? globalThis.String(object.slot1) : "",
      slot2: isSet(object.slot2) ? globalThis.String(object.slot2) : "",
      bet: isSet(object.bet) ? globalThis.Number(object.bet) : 0,
    };
  },

  toJSON(message: CalculateJackpotRequest): unknown {
    const obj: any = {};
    if (message.slot0 !== "") {
      obj.slot0 = message.slot0;
    }
    if (message.slot1 !== "") {
      obj.slot1 = message.slot1;
    }
    if (message.slot2 !== "") {
      obj.slot2 = message.slot2;
    }
    if (message.bet !== 0) {
      obj.bet = message.bet;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateJackpotRequest>, I>>(base?: I): CalculateJackpotRequest {
    return CalculateJackpotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateJackpotRequest>, I>>(object: I): CalculateJackpotRequest {
    const message = createBaseCalculateJackpotRequest();
    message.slot0 = object.slot0 ?? "";
    message.slot1 = object.slot1 ?? "";
    message.slot2 = object.slot2 ?? "";
    message.bet = object.bet ?? 0;
    return message;
  },
};

function createBaseCalculateJackpotResponse(): CalculateJackpotResponse {
  return { profit: 0, result: "", slot0: "", slot1: "", slot2: "" };
}

export const CalculateJackpotResponse: MessageFns<CalculateJackpotResponse> = {
  encode(message: CalculateJackpotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.profit !== 0) {
      writer.uint32(9).double(message.profit);
    }
    if (message.result !== "") {
      writer.uint32(18).string(message.result);
    }
    if (message.slot0 !== "") {
      writer.uint32(26).string(message.slot0);
    }
    if (message.slot1 !== "") {
      writer.uint32(34).string(message.slot1);
    }
    if (message.slot2 !== "") {
      writer.uint32(42).string(message.slot2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculateJackpotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateJackpotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.profit = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.result = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.slot0 = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.slot1 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.slot2 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateJackpotResponse {
    return {
      profit: isSet(object.profit) ? globalThis.Number(object.profit) : 0,
      result: isSet(object.result) ? globalThis.String(object.result) : "",
      slot0: isSet(object.slot0) ? globalThis.String(object.slot0) : "",
      slot1: isSet(object.slot1) ? globalThis.String(object.slot1) : "",
      slot2: isSet(object.slot2) ? globalThis.String(object.slot2) : "",
    };
  },

  toJSON(message: CalculateJackpotResponse): unknown {
    const obj: any = {};
    if (message.profit !== 0) {
      obj.profit = message.profit;
    }
    if (message.result !== "") {
      obj.result = message.result;
    }
    if (message.slot0 !== "") {
      obj.slot0 = message.slot0;
    }
    if (message.slot1 !== "") {
      obj.slot1 = message.slot1;
    }
    if (message.slot2 !== "") {
      obj.slot2 = message.slot2;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateJackpotResponse>, I>>(base?: I): CalculateJackpotResponse {
    return CalculateJackpotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateJackpotResponse>, I>>(object: I): CalculateJackpotResponse {
    const message = createBaseCalculateJackpotResponse();
    message.profit = object.profit ?? 0;
    message.result = object.result ?? "";
    message.slot0 = object.slot0 ?? "";
    message.slot1 = object.slot1 ?? "";
    message.slot2 = object.slot2 ?? "";
    return message;
  },
};

export type SlotMachineService = typeof SlotMachineService;
export const SlotMachineService = {
  randomPlay: {
    path: "/slotMachine.SlotMachine/RandomPlay",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EmptyRequest): Buffer => Buffer.from(EmptyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EmptyRequest => EmptyRequest.decode(value),
    responseSerialize: (value: RandomPlayResponse): Buffer => Buffer.from(RandomPlayResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RandomPlayResponse => RandomPlayResponse.decode(value),
  },
  calculateJackpot: {
    path: "/slotMachine.SlotMachine/CalculateJackpot",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CalculateJackpotRequest): Buffer =>
      Buffer.from(CalculateJackpotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CalculateJackpotRequest => CalculateJackpotRequest.decode(value),
    responseSerialize: (value: CalculateJackpotResponse): Buffer =>
      Buffer.from(CalculateJackpotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CalculateJackpotResponse => CalculateJackpotResponse.decode(value),
  },
} as const;

export interface SlotMachineServer extends UntypedServiceImplementation {
  randomPlay: handleUnaryCall<EmptyRequest, RandomPlayResponse>;
  calculateJackpot: handleUnaryCall<CalculateJackpotRequest, CalculateJackpotResponse>;
}

export interface SlotMachineClient extends Client {
  randomPlay(
    request: EmptyRequest,
    callback: (error: ServiceError | null, response: RandomPlayResponse) => void,
  ): ClientUnaryCall;
  randomPlay(
    request: EmptyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RandomPlayResponse) => void,
  ): ClientUnaryCall;
  randomPlay(
    request: EmptyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RandomPlayResponse) => void,
  ): ClientUnaryCall;
  calculateJackpot(
    request: CalculateJackpotRequest,
    callback: (error: ServiceError | null, response: CalculateJackpotResponse) => void,
  ): ClientUnaryCall;
  calculateJackpot(
    request: CalculateJackpotRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CalculateJackpotResponse) => void,
  ): ClientUnaryCall;
  calculateJackpot(
    request: CalculateJackpotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CalculateJackpotResponse) => void,
  ): ClientUnaryCall;
}

export const SlotMachineClient = makeGenericClientConstructor(
  SlotMachineService,
  "slotMachine.SlotMachine",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SlotMachineClient;
  service: typeof SlotMachineService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
